The PCS achieved in the new Covid problems is not good. Let's check the variance to understand what is going on.

In [1]:
import torch
from contextual_rs.test_functions.covid_exp_class import CovidSimV2

covid_arms_v3 = torch.tensor(
    [
        [0.2, 0.3],
        [0.2, 0.4],
        [0.2, 0.5],
        [0.3, 0.2],
        [0.3, 0.3],
        [0.3, 0.4],
        [0.3, 0.5],
        [0.4, 0.2],
        [0.4, 0.3],
        [0.4, 0.4],
        [0.5, 0.2],
        [0.5, 0.3],
    ]
)

sim = CovidSimV2(negate=True)

contexts = sim.context_samples

This is all contexts for a given arm.

In [6]:
X = torch.cat([covid_arms_v3[0].expand(contexts.shape[0], -1), contexts], dim=-1)

evals = torch.empty(30, contexts.shape[0])
for seed in range(1, 31):
    evals[seed-1] = sim(X, seed).view(-1)

evals.mean(dim=0), evals.std(dim=0)

(tensor([-1316.9000, -1480.7000, -1663.5333, -1921.7000, -1488.0333, -1767.0000,
         -2047.9667, -2460.6667, -1674.0333, -2063.8000, -2569.3333, -3115.2000,
         -1895.9333, -2402.7666, -3134.1333, -4148.3667]),
 tensor([ 24.5558,  36.4958,  53.2365,  79.2565,  40.9975,  46.7436,  77.0649,
         104.0856,  32.8628,  69.1407, 100.8612, 166.9797,  59.9379, 106.9694,
         170.3503, 228.2178]))

We actually care about all arms for a given context.

In [7]:
X = torch.cat([covid_arms_v3, contexts[0].expand(covid_arms_v3.shape[0], -1)], dim=-1)

evals = torch.empty(30, X.shape[0])
for seed in range(1, 31):
    evals[seed-1] = sim(X, seed).view(-1)

evals.mean(dim=0), evals.std(dim=0)

(tensor([-1316.9000, -1320.0000, -1327.4667, -1330.1666, -1326.9667, -1321.7333,
         -1338.2333, -1329.1333, -1326.9667, -1334.0667, -1336.6333, -1329.2333]),
 tensor([24.5558, 21.9780, 33.1077, 32.1270, 25.5187, 36.4871, 32.8200, 25.8053,
         21.4629, 23.0650, 26.5648, 29.1674]))

In [8]:
evals[:10].mean(dim=0), evals[:10].std(dim=0)

(tensor([-1312.4000, -1308.3000, -1319.1000, -1347.4000, -1339.3000, -1340.9000,
         -1334.4000, -1334.8000, -1338.3000, -1340.3000, -1350.4000, -1335.0000]),
 tensor([18.5604, 27.8849, 34.1937, 21.2038, 22.6129, 40.8669, 44.6024, 16.6119,
         21.1768, 22.5391, 18.2769, 27.8488]))